// Campus Accessibility Data Model

export interface CampusNode {
  id: string;
  name: string;
  category:
    | 'gate'
    | 'building'
    | 'room'
    | 'elevator'
    | 'ramp'
    | 'stairs'
    | 'washroom'
    | 'lab'
    | 'library'
    | 'canteen'
    | 'parking'
    | 'emergency'
    | 'security'
    | 'pathway'
    | 'facility';
  x: number; // 0 - 800 SVG map coordinate
  y: number; // 0 - 600 SVG map coordinate
  floor: number; // 0: ground/outdoor, 1: 1st floor, 2: 2nd floor, 3: 3rd floor
  building?: string;
  wheelchairAccessible: boolean;
  hasTactilePaving?: boolean;
  description?: string;
  features?: string[];
}

export interface CampusEdge {
  id: string;
  from: string;
  to: string;
  distance: number; // meters
  stairs: boolean;
  stairCount?: number;
  ramp: boolean;
  rampGrade?: string; // e.g. "1:14"
  elevator: boolean;
  wheelchairAccessible: boolean;
  indoor: boolean;
  doorWidthCm?: number;
  automaticDoor?: boolean;
  surfaceType?: 'smooth-paved' | 'tactile-paved' | 'asphalt' | 'interior-tile' | 'carpet' | 'gravel';
  notes?: string;
}

export interface Facility {
  id: string;
  name: string;
  category: 'washroom' | 'elevator' | 'ramp' | 'lab' | 'service' | 'sensory' | 'charging';
  location: string;
  floor: string;
  building: string;
  nodeId: string;
  wheelchairAccessible: boolean;
  openingStatus: 'Open' | 'Operational' | 'Maintenance' | 'Under Inspection';
  statusColor: 'green' | 'amber' | 'red';
  hours: string;
  doorWidth: string;
  features: string[];
  description: string;
  photoUrl: string;
  hasBraille: boolean;
  hasEmergencyCord: boolean;
  hasAutomaticDoor: boolean;
}

export interface AccessibilityIssue {
  id: string;
  type:
    | 'broken_elevator'
    | 'blocked_ramp'
    | 'stairs_maintenance'
    | 'construction'
    | 'inaccessible_entrance'
    | 'blocked_pathway'
    | 'automatic_door_failure'
    | 'other';
  location: string;
  nodeId?: string;
  edgeId?: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'reported' | 'investigating' | 'scheduled' | 'resolved';
  reportedAt: string;
  imageUrl?: string;
  upvotes: number;
}

export interface EmergencyResource {
  id: string;
  name: string;
  type: 'exit' | 'security' | 'medical' | 'shelter' | 'phone';
  location: string;
  nodeId: string;
  floor: string;
  phone?: string;
  features: string[];
  evacuationInstructions: string;
}

// Predefined Campus Graph Nodes
export const CAMPUS_NODES: CampusNode[] = [
  // Outdoor & Entrances
  {
    id: 'main-gate',
    name: 'Main Gate & Transit Plaza',
    category: 'gate',
    x: 90,
    y: 520,
    floor: 0,
    wheelchairAccessible: true,
    hasTactilePaving: true,
    description: 'Main accessible campus entryway with low-curb transit drop-off, bus shelter, and emergency blue-light station.',
    features: ['Low curb drop-off', 'Braille transit map', 'Tactile paving'],
  },
  {
    id: 'parking-a',
    name: 'Accessible Parking Lot A',
    category: 'parking',
    x: 80,
    y: 380,
    floor: 0,
    wheelchairAccessible: true,
    description: '6 designated ADA/van-accessible parking spaces with 2.4m striped transfer corridors and direct step-free path.',
    features: ['6 Van spaces', 'Direct ramp to Admin', 'Automated permit gate'],
  },
  {
    id: 'parking-b',
    name: 'Accessible Parking Lot B (East)',
    category: 'parking',
    x: 730,
    y: 470,
    floor: 0,
    wheelchairAccessible: true,
    description: '4 designated accessible bays adjacent to Science & Computer Labs with barrier-free sidewalk access.',
    features: ['4 Van spaces', 'Level asphalt', 'Direct Lab path'],
  },
  {
    id: 'security-desk',
    name: 'Campus Security & Welcome Desk',
    category: 'security',
    x: 170,
    y: 490,
    floor: 0,
    wheelchairAccessible: true,
    description: '24/7 Security checkpoint, mobility assistance golf-cart dispatch, and emergency help desk.',
    features: ['24/7 Help Desk', 'Mobility Cart Dispatch', 'Emergency AED Unit'],
  },

  // Admin Building
  {
    id: 'admin-ramp',
    name: 'Admin Building South Ramp',
    category: 'ramp',
    x: 230,
    y: 430,
    floor: 0,
    building: 'Hall of Administration',
    wheelchairAccessible: true,
    description: 'ADA-compliant concrete ramp with 1:14 slope, double continuous handrails, and non-slip textured finish.',
    features: ['Slope 1:14', 'Dual Handrails', 'LED Floor Lighting'],
  },
  {
    id: 'admin-stairs',
    name: 'Admin Building Grand Steps',
    category: 'stairs',
    x: 250,
    y: 460,
    floor: 0,
    building: 'Hall of Administration',
    wheelchairAccessible: false,
    description: 'Historic stone flight of 16 steps leading to Admin portico. No elevator access along this facade.',
    features: ['16 Stone Steps', 'High Risers (18cm)', 'Not Wheelchair Accessible'],
  },
  {
    id: 'admin-lobby',
    name: 'Admin Building - Main Lobby',
    category: 'building',
    x: 280,
    y: 410,
    floor: 0,
    building: 'Hall of Administration',
    wheelchairAccessible: true,
    description: 'Ground floor main hall, Registrar counter with lowered wheelchair section, Disability Support Services office.',
    features: ['Lowered counter (76cm)', 'Automatic motion doors', 'Disability Support Office (Room 102)'],
  },
  {
    id: 'admin-elevator',
    name: 'Admin Building Elevator',
    category: 'elevator',
    x: 310,
    y: 400,
    floor: 0,
    building: 'Hall of Administration',
    wheelchairAccessible: true,
    description: 'High-speed passenger elevator connecting Floors G, 1, and 2. Auditory voice prompts and braille buttons.',
    features: ['Braille buttons', 'Audio floor announcer', 'Door dwell time 7s', 'Capacity: 1200kg'],
  },

  // Central Quad
  {
    id: 'central-quad',
    name: 'Central Quadrangle Plaza',
    category: 'pathway',
    x: 410,
    y: 380,
    floor: 0,
    wheelchairAccessible: true,
    hasTactilePaving: true,
    description: 'Paved outdoor quad connecting all major academic zones. Wide step-free concrete pathways with rest benches.',
    features: ['100% Step-free', 'Tactile guideline strips', 'Shaded rest pods every 40m'],
  },

  // Library
  {
    id: 'library-ramp',
    name: 'University Library Accessible Ramp',
    category: 'ramp',
    x: 330,
    y: 270,
    floor: 0,
    building: 'Williamson Memorial Library',
    wheelchairAccessible: true,
    description: 'Gentle winding ramp with 1:16 slope, heated surface for winter safety, leads to automatic sliding glass entrance.',
    features: ['Slope 1:16', 'Continuous handrails', 'Snow-melting heat wires'],
  },
  {
    id: 'library-stairs',
    name: 'Library Front Terrace Steps',
    category: 'stairs',
    x: 290,
    y: 280,
    floor: 0,
    building: 'Williamson Memorial Library',
    wheelchairAccessible: false,
    description: 'Steep entrance staircase with 22 granite steps.',
    features: ['22 Steps', 'High riser', 'No ramp directly adjacent'],
  },
  {
    id: 'library-entrance',
    name: 'University Library Ground Lobby',
    category: 'library',
    x: 340,
    y: 220,
    floor: 0,
    building: 'Williamson Memorial Library',
    wheelchairAccessible: true,
    description: 'Main library hub, accessible checkout desk, braille terminals, adaptive screen reading work suites.',
    features: ['Screen readers (JAWS)', 'Height-adjustable desks', 'Assistive technology desk'],
  },
  {
    id: 'library-elevator',
    name: 'Library Central Elevator',
    category: 'elevator',
    x: 380,
    y: 200,
    floor: 0,
    building: 'Williamson Memorial Library',
    wheelchairAccessible: true,
    description: 'Glass-walled accessible elevator serving Ground, 1st, 2nd, and 3rd floors.',
    features: ['Braille floor pad', 'Wide door (100cm)', 'Voice assistance'],
  },
  {
    id: 'library-fl2-sensory',
    name: 'Library 2nd Floor Sensory & Quiet Room',
    category: 'facility',
    x: 380,
    y: 170,
    floor: 2,
    building: 'Williamson Memorial Library',
    wheelchairAccessible: true,
    description: 'Sensory decompression space with dimmable warm lights, noise-cancellation headphones, and ergonomic seating.',
    features: ['Sensory safe', 'Wheelchair quiet study bay', 'Elevator direct access'],
  },

  // Academic Building
  {
    id: 'academic-ramp',
    name: 'Academic Building West Ramp',
    category: 'ramp',
    x: 500,
    y: 260,
    floor: 0,
    building: 'Academic Hall',
    wheelchairAccessible: true,
    description: 'Covered accessible ramp leading to West wing automatic entrance.',
    features: ['Slope 1:12', 'Weather canopy', 'Motion-activated power door'],
  },
  {
    id: 'academic-stairs',
    name: 'Academic Hall Main Steps',
    category: 'stairs',
    x: 540,
    y: 270,
    floor: 0,
    building: 'Academic Hall',
    wheelchairAccessible: false,
    description: 'Main colonnade stairs with 20 stone steps.',
    features: ['20 Steps', 'Not accessible'],
  },
  {
    id: 'academic-lobby',
    name: 'Academic Hall - Ground Lobby',
    category: 'building',
    x: 530,
    y: 220,
    floor: 0,
    building: 'Academic Hall',
    wheelchairAccessible: true,
    description: 'Spacious corridor with tactile maps and high-contrast color wall ribbons for low-vision guidance.',
    features: ['Wide halls (2.5m)', 'Tactile directional signage', 'Rest benches'],
  },
  {
    id: 'academic-elevator',
    name: 'Academic Hall Central Elevator',
    category: 'elevator',
    x: 570,
    y: 200,
    floor: 0,
    building: 'Academic Hall',
    wheelchairAccessible: true,
    description: 'Spacious accessible elevator serving all floors (G to 3rd floor).',
    features: ['Braille panel at 90cm height', 'Mirror for rear exit visibility', 'Clear audio cues'],
  },
  {
    id: 'academic-room-305',
    name: 'Academic Hall - Room 305',
    category: 'room',
    x: 580,
    y: 150,
    floor: 3,
    building: 'Academic Hall',
    wheelchairAccessible: true,
    description: 'Smart Lecture Theatre with motorized tiered seating access, audio induction hearing loop, and wide desks.',
    features: ['Dedicated wheelchair desk spots', 'Hearing loop installed', 'Step-free entrance'],
  },
  {
    id: 'academic-washroom-fl2',
    name: 'Academic Hall - Accessible Washroom (2nd Floor)',
    category: 'washroom',
    x: 540,
    y: 170,
    floor: 2,
    building: 'Academic Hall',
    wheelchairAccessible: true,
    description: 'Universal gender-neutral accessible restroom with automatic door opener, ceiling hoist anchor, and red emergency pull cord.',
    features: ['Emergency pull cord', 'Adult changing table', 'Grab bars both sides', 'Push-button door'],
  },

  // Science & Computer Complex
  {
    id: 'science-ramp',
    name: 'Science Complex East Ramp',
    category: 'ramp',
    x: 630,
    y: 330,
    floor: 0,
    building: 'Science & Engineering Complex',
    wheelchairAccessible: true,
    description: 'Wide concrete ramp with non-slip texture, connecting quad level to science entrance.',
    features: ['Slope 1:14', 'Direct Lab path', 'Illuminated at night'],
  },
  {
    id: 'science-lobby',
    name: 'Science Complex - Central Atrium',
    category: 'building',
    x: 660,
    y: 320,
    floor: 0,
    building: 'Science & Engineering Complex',
    wheelchairAccessible: true,
    description: 'Bright atrium with tactile floor trails leading to elevators and lab suites.',
    features: ['Tactile floor path', 'Low information kiosk', 'Auto doors'],
  },
  {
    id: 'computer-lab',
    name: 'Advanced Computer Engineering Lab (Lab 101)',
    category: 'lab',
    x: 710,
    y: 310,
    floor: 0,
    building: 'Science & Engineering Complex',
    wheelchairAccessible: true,
    description: 'Modern computing lab equipped with motorized sit-stand desks, eye-tracking input peripherals, and ergonomic mice.',
    features: ['4 Sit-stand electric desks', 'Wide 1.2m aisles', 'Screen magnification software'],
  },
  {
    id: 'electronics-lab',
    name: 'Robotics & Electronics Laboratory',
    category: 'lab',
    x: 710,
    y: 370,
    floor: 0,
    building: 'Science & Engineering Complex',
    wheelchairAccessible: true,
    description: 'Hardware lab with low-profile soldering ventilation stations and accessible workbench equipment.',
    features: ['Accessible soldering stations', 'Smooth ESD flooring', 'Spacious turning radius'],
  },
  {
    id: 'science-elevator',
    name: 'Science Complex Heavy-Duty Elevator',
    category: 'elevator',
    x: 680,
    y: 280,
    floor: 0,
    building: 'Science & Engineering Complex',
    wheelchairAccessible: true,
    description: 'Freight & passenger combination elevator with wide double doors (120cm).',
    features: ['120cm door width', 'Heavy payload (1600kg)', 'Low-mounted buttons'],
  },

  // Student Activity Centre & Dining
  {
    id: 'sac-ramp',
    name: 'Student Activity Centre (SAC) Ramp',
    category: 'ramp',
    x: 440,
    y: 480,
    floor: 0,
    building: 'Student Activity Centre',
    wheelchairAccessible: true,
    description: 'Wide entryway ramp with 1:12 slope and level rest landings every 6 meters.',
    features: ['Rest landings', 'Non-slip rubber grid', 'Handrails on both sides'],
  },
  {
    id: 'sac-stairs',
    name: 'SAC Plaza Steps',
    category: 'stairs',
    x: 480,
    y: 470,
    floor: 0,
    building: 'Student Activity Centre',
    wheelchairAccessible: false,
    description: 'Stepped amphitheater-style plaza stairs with 14 steps.',
    features: ['14 Steps', 'No ramp in center'],
  },
  {
    id: 'sac-main',
    name: 'Student Activity Centre & Lounge',
    category: 'building',
    x: 490,
    y: 520,
    floor: 0,
    building: 'Student Activity Centre',
    wheelchairAccessible: true,
    description: 'Hub for student clubs, disability advocate office, motorized wheelchair fast-charging stations, and recreational spaces.',
    features: ['Wheelchair fast charger (24V/48V)', 'Inclusive gaming rigs', 'Accessible reception'],
  },
  {
    id: 'auditorium',
    name: 'University Grand Auditorium',
    category: 'facility',
    x: 580,
    y: 510,
    floor: 0,
    building: 'Student Activity Centre',
    wheelchairAccessible: true,
    description: '1,200-seat theater with step-free floor level, removable seating bays for wheelchairs, and stage ramp.',
    features: ['Ramp to stage', '12 Accessible companion spaces', 'Induction loop T-coil'],
  },
  {
    id: 'canteen',
    name: 'Campus Dining Canteen & Café',
    category: 'canteen',
    x: 350,
    y: 540,
    floor: 0,
    wheelchairAccessible: true,
    description: 'Food court with low counter ordering stations, wide tray slides, and tables designed for wheelchair clearance.',
    features: ['Wheelchair clearance tables', 'Lowered ordering counter', 'Braille and large print menus'],
  },
  {
    id: 'accessible-washroom-quad',
    name: 'Quad Central Accessible Washroom',
    category: 'washroom',
    x: 390,
    y: 430,
    floor: 0,
    wheelchairAccessible: true,
    description: 'Standalone accessible comfort station with motion sensor lock, hoist, and emergency assistance intercom.',
    features: ['All-Gender', 'Ceiling track ready', 'Emergency call intercom', 'Baby changing station'],
  },

  // Emergency Exits & Points
  {
    id: 'emergency-exit-west',
    name: 'West Campus Accessible Evacuation Gate',
    category: 'emergency',
    x: 120,
    y: 310,
    floor: 0,
    wheelchairAccessible: true,
    description: 'Emergency exit with push-bar panic hardware, zero threshold ramp, and illuminated beacon.',
    features: ['Zero threshold', 'Flashing beacon', 'Direct connection to safe street'],
  },
  {
    id: 'emergency-exit-east',
    name: 'East Science Evacuation Refuge Zone',
    category: 'emergency',
    x: 740,
    y: 260,
    floor: 0,
    wheelchairAccessible: true,
    description: 'Fire-resistant area of rescue assistance with 2-way emergency intercom directly to 911 dispatch.',
    features: ['Area of Rescue Assistance', 'Two-way intercom', 'Evac-chair equipped'],
  }
];

// Graph Edges Connecting Campus Nodes
export const CAMPUS_EDGES: CampusEdge[] = [
  // From Main Gate
  {
    id: 'e-gate-sec',
    from: 'main-gate',
    to: 'security-desk',
    distance: 40,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'tactile-paved',
    notes: 'Level sidewalk with tactile guidance and low slope (1:30).',
  },
  {
    id: 'e-gate-parking-a',
    from: 'main-gate',
    to: 'parking-a',
    distance: 65,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Direct wide sidewalk with curb cuts.',
  },
  {
    id: 'e-gate-canteen',
    from: 'main-gate',
    to: 'canteen',
    distance: 95,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Gentle grade outdoor promenade directly to dining patio.',
  },

  // From Security Desk to Admin
  {
    id: 'e-sec-admin-ramp',
    from: 'security-desk',
    to: 'admin-ramp',
    distance: 55,
    stairs: false,
    ramp: true,
    rampGrade: '1:14',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Gentle approach to ADA ramp with stainless handrails.',
  },
  {
    id: 'e-sec-admin-stairs',
    from: 'security-desk',
    to: 'admin-stairs',
    distance: 45,
    stairs: true,
    stairCount: 16,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Direct shortcut via 16 steep stone steps.',
  },
  {
    id: 'e-admin-ramp-lobby',
    from: 'admin-ramp',
    to: 'admin-lobby',
    distance: 25,
    stairs: false,
    ramp: true,
    rampGrade: '1:14',
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    automaticDoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Automatic sliding glass doors with push plate.',
  },
  {
    id: 'e-admin-stairs-lobby',
    from: 'admin-stairs',
    to: 'admin-lobby',
    distance: 20,
    stairs: true,
    stairCount: 16,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: true,
    doorWidthCm: 90,
    surfaceType: 'interior-tile',
    notes: 'Manual heavy push doors at top of grand staircase.',
  },
  {
    id: 'e-admin-lobby-elevator',
    from: 'admin-lobby',
    to: 'admin-elevator',
    distance: 20,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Level marble hallway, 3m wide.',
  },

  // Admin to Quad
  {
    id: 'e-admin-lobby-quad',
    from: 'admin-lobby',
    to: 'central-quad',
    distance: 60,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    automaticDoor: true,
    doorWidthCm: 105,
    surfaceType: 'smooth-paved',
    notes: 'Exit onto Central Quad via flush threshold sliding door.',
  },
  {
    id: 'e-admin-quad-washroom',
    from: 'admin-lobby',
    to: 'accessible-washroom-quad',
    distance: 50,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Direct paved pathway to central comfort facility.',
  },
  {
    id: 'e-quad-washroom',
    from: 'central-quad',
    to: 'accessible-washroom-quad',
    distance: 35,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'tactile-paved',
    notes: 'Tactile paved trail from central plaza to washroom entrance.',
  },

  // Quad to Library
  {
    id: 'e-quad-library-ramp',
    from: 'central-quad',
    to: 'library-ramp',
    distance: 70,
    stairs: false,
    ramp: true,
    rampGrade: '1:16',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Wide 2.4m smooth concrete avenue to accessible ramp.',
  },
  {
    id: 'e-quad-library-stairs',
    from: 'central-quad',
    to: 'library-stairs',
    distance: 50,
    stairs: true,
    stairCount: 22,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Direct shortcut via 22 granite steps.',
  },
  {
    id: 'e-lib-ramp-entrance',
    from: 'library-ramp',
    to: 'library-entrance',
    distance: 30,
    stairs: false,
    ramp: true,
    rampGrade: '1:16',
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    automaticDoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Level entry into library lobby through automated power sensor.',
  },
  {
    id: 'e-lib-stairs-entrance',
    from: 'library-stairs',
    to: 'library-entrance',
    distance: 25,
    stairs: true,
    stairCount: 22,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Heavy revolving and turnstile doors at top of steps.',
  },
  {
    id: 'e-lib-entrance-elevator',
    from: 'library-entrance',
    to: 'library-elevator',
    distance: 25,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'carpet',
    notes: 'Low-pile commercial carpet with very low rolling resistance.',
  },
  {
    id: 'e-lib-elev-sensory',
    from: 'library-elevator',
    to: 'library-fl2-sensory',
    distance: 15,
    stairs: false,
    ramp: false,
    elevator: true,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'carpet',
    notes: 'Take elevator up to Level 2. Sensory room is 10 steps from elevator door.',
  },

  // Library to Academic Hall
  {
    id: 'e-lib-academic-path',
    from: 'library-entrance',
    to: 'academic-ramp',
    distance: 85,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Connecting North Colonnade path, flat and well-lit.',
  },
  {
    id: 'e-quad-academic-ramp',
    from: 'central-quad',
    to: 'academic-ramp',
    distance: 65,
    stairs: false,
    ramp: true,
    rampGrade: '1:12',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Accessible covered walkway leading directly to West Ramp.',
  },
  {
    id: 'e-quad-academic-stairs',
    from: 'central-quad',
    to: 'academic-stairs',
    distance: 45,
    stairs: true,
    stairCount: 20,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Colonnade monumental staircase (20 steps).',
  },
  {
    id: 'e-acad-ramp-lobby',
    from: 'academic-ramp',
    to: 'academic-lobby',
    distance: 25,
    stairs: false,
    ramp: true,
    rampGrade: '1:12',
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    automaticDoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Accessible power door leading into Academic Lobby.',
  },
  {
    id: 'e-acad-stairs-lobby',
    from: 'academic-stairs',
    to: 'academic-lobby',
    distance: 20,
    stairs: true,
    stairCount: 20,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Heavy swing doors at top of steps.',
  },
  {
    id: 'e-acad-lobby-elevator',
    from: 'academic-lobby',
    to: 'academic-elevator',
    distance: 25,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Main hallway straight to Central Elevator.',
  },
  {
    id: 'e-acad-elev-room305',
    from: 'academic-elevator',
    to: 'academic-room-305',
    distance: 30,
    stairs: false,
    ramp: false,
    elevator: true,
    wheelchairAccessible: true,
    indoor: true,
    doorWidthCm: 100,
    surfaceType: 'interior-tile',
    notes: 'Elevator up to Floor 3. Hallway is level and 2.4m wide to Room 305.',
  },
  {
    id: 'e-acad-stairs-room305',
    from: 'academic-lobby',
    to: 'academic-room-305',
    distance: 40,
    stairs: true,
    stairCount: 48,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Two flights of fire stairs (48 steps total) connecting G to Floor 3.',
  },
  {
    id: 'e-acad-elev-washroom',
    from: 'academic-elevator',
    to: 'academic-washroom-fl2',
    distance: 20,
    stairs: false,
    ramp: false,
    elevator: true,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Elevator to Floor 2. Accessible washroom right around the corner.',
  },

  // Academic to Science Complex
  {
    id: 'e-acad-science-ramp',
    from: 'academic-lobby',
    to: 'science-ramp',
    distance: 70,
    stairs: false,
    ramp: true,
    rampGrade: '1:14',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Covered glass connector breezeway between Academic and Science.',
  },
  {
    id: 'e-quad-science-ramp',
    from: 'central-quad',
    to: 'science-ramp',
    distance: 60,
    stairs: false,
    ramp: true,
    rampGrade: '1:14',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Diagonal accessible path across the eastern quad lawn.',
  },
  {
    id: 'e-sci-ramp-lobby',
    from: 'science-ramp',
    to: 'science-lobby',
    distance: 20,
    stairs: false,
    ramp: true,
    rampGrade: '1:14',
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    automaticDoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Sliding glass entryway into Science Complex Atrium.',
  },
  {
    id: 'e-sci-lobby-lab',
    from: 'science-lobby',
    to: 'computer-lab',
    distance: 30,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    doorWidthCm: 105,
    surfaceType: 'interior-tile',
    notes: 'Straight corridor with automatic pocket door into Lab 101.',
  },
  {
    id: 'e-sci-lobby-electronics',
    from: 'science-lobby',
    to: 'electronics-lab',
    distance: 35,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    doorWidthCm: 105,
    surfaceType: 'interior-tile',
    notes: 'Ground level wide hallway with tactile guidance strip.',
  },
  {
    id: 'e-sci-lobby-elevator',
    from: 'science-lobby',
    to: 'science-elevator',
    distance: 25,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Corridor to heavy duty elevator.',
  },
  {
    id: 'e-sci-parking-b',
    from: 'science-lobby',
    to: 'parking-b',
    distance: 55,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Direct ramp-free exit to East Accessible Parking bays.',
  },

  // Student Activity Centre (SAC) & Canteen
  {
    id: 'e-quad-sac-ramp',
    from: 'central-quad',
    to: 'sac-ramp',
    distance: 50,
    stairs: false,
    ramp: true,
    rampGrade: '1:12',
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Gentle landscaped terrace to SAC accessible ramp.',
  },
  {
    id: 'e-quad-sac-stairs',
    from: 'central-quad',
    to: 'sac-stairs',
    distance: 40,
    stairs: true,
    stairCount: 14,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Sunken plaza steps leading to SAC entrance.',
  },
  {
    id: 'e-sac-ramp-main',
    from: 'sac-ramp',
    to: 'sac-main',
    distance: 25,
    stairs: false,
    ramp: true,
    rampGrade: '1:12',
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    automaticDoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Large automatic double sliding doors.',
  },
  {
    id: 'e-sac-stairs-main',
    from: 'sac-stairs',
    to: 'sac-main',
    distance: 20,
    stairs: true,
    stairCount: 14,
    ramp: false,
    elevator: false,
    wheelchairAccessible: false,
    indoor: true,
    surfaceType: 'interior-tile',
    notes: 'Manual heavy revolving doors.',
  },
  {
    id: 'e-sac-auditorium',
    from: 'sac-main',
    to: 'auditorium',
    distance: 45,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    doorWidthCm: 120,
    surfaceType: 'carpet',
    notes: 'Direct step-free interior corridor into main hall seating.',
  },
  {
    id: 'e-sac-canteen',
    from: 'sac-main',
    to: 'canteen',
    distance: 55,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Level breezeway with covered overhead canopy.',
  },
  {
    id: 'e-canteen-quad',
    from: 'canteen',
    to: 'central-quad',
    distance: 60,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Wide pedestrian plaza between dining hall and green quad.',
  },

  // Emergency Exits Connections
  {
    id: 'e-parking-a-emg',
    from: 'parking-a',
    to: 'emergency-exit-west',
    distance: 35,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: false,
    surfaceType: 'smooth-paved',
    notes: 'Clear level path to West Emergency evacuation gate.',
  },
  {
    id: 'e-sci-emg',
    from: 'science-lobby',
    to: 'emergency-exit-east',
    distance: 40,
    stairs: false,
    ramp: false,
    elevator: false,
    wheelchairAccessible: true,
    indoor: true,
    doorWidthCm: 110,
    surfaceType: 'interior-tile',
    notes: 'Direct fire exit corridor to Area of Rescue Assistance.',
  }
];

// Predefined Accessible Campus Facilities
export const CAMPUS_FACILITIES: Facility[] = [
  {
    id: 'fac-washroom-1',
    name: 'Quad Central Universal Accessible Washroom',
    category: 'washroom',
    location: 'Central Quadrangle, Pavilion South',
    floor: 'Ground Floor',
    building: 'Quad Pavilion',
    nodeId: 'accessible-washroom-quad',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '24/7 Accessible Keycard Access',
    doorWidth: '105 cm (Automatic)',
    features: ['Electric ceiling hoist', 'Adult changing table', 'Dual height grab bars', 'Red emergency cord', 'Anti-scald faucet'],
    description: 'Premier accessible restroom meeting universal design standards. Features plenty of maneuvering space for power wheelchairs.',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: true,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-washroom-2',
    name: 'Academic Hall - 2nd Floor Accessible Restroom',
    category: 'washroom',
    location: 'Academic Hall, Room 215B',
    floor: '2nd Floor',
    building: 'Academic Hall',
    nodeId: 'academic-washroom-fl2',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '7:00 AM – 10:00 PM',
    doorWidth: '98 cm',
    features: ['Fold-down grab bars', 'Emergency call button', 'Automated soap and towels', 'Large mirror tilted for seated height'],
    description: 'Spacious accessible restroom located right next to the central elevator on the 2nd floor.',
    photoUrl: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: true,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-elev-1',
    name: 'Williamson Library High-Speed Accessible Elevator',
    category: 'elevator',
    location: 'Central Library Atrium',
    floor: 'Floors G, 1, 2, 3',
    building: 'Williamson Memorial Library',
    nodeId: 'library-elevator',
    wheelchairAccessible: true,
    openingStatus: 'Operational',
    statusColor: 'green',
    hours: '8:00 AM – Midnight',
    doorWidth: '100 cm',
    features: ['Voice floor announcements', 'Braille call buttons at 90cm', 'Interior mirrors', 'Emergency hands-free telephone'],
    description: 'Spacious glass-walled elevator providing access to all collection floors, study carrels, and the sensory quiet room.',
    photoUrl: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-elev-2',
    name: 'Academic Hall Central Elevator',
    category: 'elevator',
    location: 'Academic Hall West Core',
    floor: 'Floors G, 1, 2, 3',
    building: 'Academic Hall',
    nodeId: 'academic-elevator',
    wheelchairAccessible: true,
    openingStatus: 'Operational',
    statusColor: 'green',
    hours: '6:30 AM – 11:00 PM',
    doorWidth: '95 cm',
    features: ['Extended door dwell time (8s)', 'Tactile floor indicator', 'Auditory arrival chime', 'Emergency battery lowering'],
    description: 'Crucial elevator providing step-free transit to Lecture Room 305 and faculty offices on upper floors.',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-elev-3',
    name: 'Science Complex Heavy-Duty Lift',
    category: 'elevator',
    location: 'Science Complex Core North',
    floor: 'Floors G, 1, 2',
    building: 'Science & Engineering Complex',
    nodeId: 'science-elevator',
    wheelchairAccessible: true,
    openingStatus: 'Operational',
    statusColor: 'green',
    hours: '24/7 with Student ID',
    doorWidth: '120 cm',
    features: ['Extra wide 120cm doors', 'Level leveling accuracy within 5mm', '1600kg capacity'],
    description: 'Dual-access elevator allowing direct access between engineering labs and outdoor courtyard.',
    photoUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-ramp-1',
    name: 'Williamson Library Heated North Ramp',
    category: 'ramp',
    location: 'Library Main Entrance North',
    floor: 'Ground',
    building: 'Williamson Memorial Library',
    nodeId: 'library-ramp',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '24/7',
    doorWidth: '220 cm pathway',
    features: ['Slope 1:16 (Very Gentle)', 'Dual-height handrails', 'Snow melting embedded radiant heat', 'Slip-resistant brushed granite'],
    description: 'Designed to bypass the 22 front terrace steps with an exceptionally smooth, low-effort grade.',
    photoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: false,
  },
  {
    id: 'fac-ramp-2',
    name: 'Admin Building South Ramp',
    category: 'ramp',
    location: 'Hall of Administration West Entrance',
    floor: 'Ground',
    building: 'Hall of Administration',
    nodeId: 'admin-ramp',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '24/7',
    doorWidth: '180 cm pathway',
    features: ['Slope 1:14', 'Continuous handrails', 'Covered glass portico', 'Direct push-button entrance door'],
    description: 'Direct step-free connection from Parking Lot A to the Registrar and Disability Services.',
    photoUrl: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: false,
  },
  {
    id: 'fac-lab-1',
    name: 'Accessible Computing & Assistive Tech Lab (Lab 101)',
    category: 'lab',
    location: 'Science Complex, Ground Floor Room 101',
    floor: 'Ground Floor',
    building: 'Science & Engineering Complex',
    nodeId: 'computer-lab',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '8:00 AM – 11:00 PM',
    doorWidth: '105 cm',
    features: ['Motorized sit-stand desks', 'JAWS and NVDA screen reading rigs', 'Eye-gaze and trackball inputs', 'Braille embosser printer'],
    description: 'Fully equipped assistive technology laboratory with trained accessibility aides on duty from 9 AM to 5 PM.',
    photoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: true,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-charging-1',
    name: 'Electric Wheelchair Fast-Charging Station',
    category: 'charging',
    location: 'Student Activity Centre (SAC) Lounge',
    floor: 'Ground Floor',
    building: 'Student Activity Centre',
    nodeId: 'sac-main',
    wheelchairAccessible: true,
    openingStatus: 'Operational',
    statusColor: 'green',
    hours: '24/7 Accessible',
    doorWidth: 'Wide open lounge',
    features: ['High-amperage 24V & 48V wheelchair plugs', 'Standard USB-C device chargers', 'Tire inflation pump', 'Comfortable seating area'],
    description: 'Free dedicated recharging station for power wheelchair users. Includes rapid chargers compatible with major power-chair manufacturers.',
    photoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: false,
    hasAutomaticDoor: true,
  },
  {
    id: 'fac-sensory-1',
    name: 'Neurodivergent & Sensory Decompression Room',
    category: 'sensory',
    location: 'Williamson Library, 2nd Floor Room 240',
    floor: '2nd Floor',
    building: 'Williamson Memorial Library',
    nodeId: 'library-fl2-sensory',
    wheelchairAccessible: true,
    openingStatus: 'Open',
    statusColor: 'green',
    hours: '8:00 AM – 10:00 PM',
    doorWidth: '100 cm',
    features: ['Acoustic sound damping', 'Dimmable warm amber lighting', 'Weighted blankets & sensory fidgets', 'Zero fluorescent flicker'],
    description: 'Quiet sanctuary designed for students with autism, ADHD, PTSD, or sensory overload to recharge in comfort.',
    photoUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
    hasBraille: true,
    hasEmergencyCord: true,
    hasAutomaticDoor: true,
  }
];

// Initial Reported Accessibility Barriers/Issues (Seed Data)
export const INITIAL_ISSUES: AccessibilityIssue[] = [
  {
    id: 'rep-001',
    type: 'broken_elevator',
    location: 'Academic Hall - East Auxiliary Lift',
    nodeId: 'academic-elevator',
    edgeId: 'e-acad-elev-room305',
    description: 'Routine maintenance underway on cables. Central Main elevator remains 100% operational as alternate route.',
    severity: 'medium',
    status: 'scheduled',
    reportedAt: '2026-10-02T14:30:00Z',
    upvotes: 8,
  },
  {
    id: 'rep-002',
    type: 'blocked_pathway',
    location: 'North Walkway between Library and Science',
    description: 'Tree branch pruning operation temporarily narrows walkway to 90cm. Signage directs wheelchairs to Central Quad avenue.',
    severity: 'low',
    status: 'investigating',
    reportedAt: '2026-10-02T16:15:00Z',
    upvotes: 4,
  },
  {
    id: 'rep-003',
    type: 'automatic_door_failure',
    location: 'SAC East Side Automated Entrance',
    description: 'Push pad actuator button is intermittently sticking. West Main sliding doors working normally.',
    severity: 'medium',
    status: 'reported',
    reportedAt: '2026-10-02T18:00:00Z',
    upvotes: 11,
  }
];

// Emergency Accessibility Resources
export const EMERGENCY_RESOURCES: EmergencyResource[] = [
  {
    id: 'emg-1',
    name: 'Campus Police & Disability Crisis Response',
    type: 'security',
    location: 'Security Welcome Centre (Main Gate)',
    nodeId: 'security-desk',
    floor: 'Ground',
    phone: '+1 (555) 019-9111',
    features: ['24/7 Dispatch', 'GPS Disability Escort', 'AED & Wheelchair Van On Call'],
    evacuationInstructions: 'Call or press blue-light button. An accessible transport van will be dispatched to your location.',
  },
  {
    id: 'emg-2',
    name: 'East Science Complex Area of Rescue Assistance',
    type: 'shelter',
    location: 'Science Complex, 2nd Floor East Stairwell Enclosure',
    nodeId: 'emergency-exit-east',
    floor: '2nd Floor',
    phone: 'Direct 2-way callbox inside refuge area',
    features: ['2-hour fire-rated walls', 'Fresh air positive pressurization', 'Evacuation stair chair (Evac-Chair 300H)'],
    evacuationInstructions: 'Move into the designated refuge zone. Press the callbox button to alert fire command of your exact room location.',
  },
  {
    id: 'emg-3',
    name: 'Campus Student Health & Urgent Care Center',
    type: 'medical',
    location: 'Hall of Administration, Ground Floor East Suite',
    nodeId: 'admin-lobby',
    floor: 'Ground',
    phone: '+1 (555) 019-4357',
    features: ['Nurse on duty', 'Crutches, loaner wheelchairs', 'Oxygen support', 'Sensory quiet triage'],
    evacuationInstructions: 'Accessible ground-level entrance with direct ambulance turnaround bay.',
  },
  {
    id: 'emg-4',
    name: 'West Campus Step-Free Emergency Evacuation Gate',
    type: 'exit',
    location: 'Perimeter West Fence near Lot A',
    nodeId: 'emergency-exit-west',
    floor: 'Ground',
    features: ['Panic push-bar opening', 'Zero-lip asphalt connection', 'Emergency blue beacon light'],
    evacuationInstructions: 'Primary accessible outdoor evacuation egress. Opens onto wide city sidewalk free of vehicular traffic.',
  }
];
